# Generated by Django 4.1.7 on 2024-08-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dafiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
